version: 2.1
executors:
  python-3-7:
    docker:
      - image: circleci/python:3.7
jobs:
  build-and-test:
    executor: python-3-7
    steps:
      - checkout
      - restore_cache:
          keys:
            - python-cache-{{ checksum "requirements.txt" }}
      - run:
          name: install dependencies
          command: |
            python -m pip install -r requirements.txt --user

            # OpenMP setup
            echo "setting up OpenMP"
            sudo apt install libomp-dev && sudo apt show libomp-dev

            export OMP_NUM_THREADS="2"
            python -m pip install . --user
      - save_cache:
          paths:
            - ~/.cache/pip
          key: python-cache-{{ checksum "requirements.txt" }}
          when: always
      - run:
          name: run unit tests
          command: |
            python -m pytest -v tests --cov=${CIRCLE_PROJECT_REPONAME/-/_} --cov-report xml

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
